### ISSUE TITLE
Hi 小宝，及各位开发者： 一个建议

### ISSUE THREAD

**Issue by gdillainepub** [koolshare/firmware#1]
可否在github上也存放各版本的firmware（而不要只在论坛上发布百度网盘链接啊）以及有关的文档(based on Merlin xxxx， changelog etc.) 谢谢！

**Comment by gdillainepub** [comment]
补充：包括旧的版本。。。如6.3甚至更早。。。谢谢

**Comment by sadoneli** [comment]
这个项目就是为这个准备的，之前请到一位朋友来做，但是他貌似比较忙一直没空做

**Comment by jannson** [comment]
恩，这个项目正式开始了！！！
