### ISSUE TITLE
关于Chromecast支持选项实现的不完整的Bug反馈

### ISSUE THREAD

**Issue by FlyingGitHub** [koolshare/firmware#3]
if [ "$ss_basic_chromecast" == "1" ]; then
echo $(date): enable lan dns take over, i.e chromecast...
iptables -t nat -A PREROUTING -s $lan_ipaddr/24 -p udp --dport 53 -j DNAT --to $lan_ipaddr >/dev/null 2>&1
echo $(date): done
echo $(date):
看了下目前脚本中实现内网DNS劫持的部分（Chromecast支持选项），貌似没有把连上路由器的VPN客户端IP地址池加上去，是不是可以考虑在下次规则更新中加上（PPTP客户端默认IP地址范围是192.168.10.0/24，当然还有openvpn等）

**Comment by jannson** [comment]
把这个地址直接去掉，劫持所有的好了？

**Comment by FlyingGitHub** [comment]
也是不错的思路，下次ss升级时能修正好吗？

**Comment by jannson** [comment]
我提给 S大让它来修复。

**Comment by FlyingGitHub** [comment]
恩，目前版本1.5.7还是没有解决这个问题。

**Comment by jannson** [comment]
恩？情提给他了。我再让他看看。

**Comment by FlyingGitHub** [comment]
感谢，从2.0开始就修正了。
