### ISSUE TITLE
修改版Merlin固件的**完整**开源代码公布在哪里？

### ISSUE THREAD

**Issue by goodbest** [koolshare/firmware#4]
As the released firmwares are based on Asus-merlin, I think **ALL** the modified firmware codes (including the firmware codes and building files) should be publicly available according to the [License](https://github.com/RMerl/asuswrt-merlin/blob/master/License).

But right now, I can only find the [codes of plugins](https://github.com/koolshare/koolshare.github.io) that you are working on. I think it's not enough to fulfill the License requirement.

**Comment by jannson** [comment]
我们会在合适的时间去开源整个代码，目前我们也在按节奏进行中。
asus merlin 对 R7K / R6300v2 的封杀越来越严重，我们通过各种 hack 才能使用无线驱动。然后 asus 下期新代码又进行更严格驱动封闭方法。一开源直接导致未来无法在新代码 支持 R7K / R6300v2 / R6900 。
这个也是国外 V 神很早就不再开放他新代码的原因。这个你可以去确认下。

接下来我们会有两个工作：

1. 让我们的插件中心直接支持 asus merlin 官方固件，并且不会再修改任何 asus merlin 的代码。用户直接刷官方固件就可以了。

2.  在 tomato 去支持 R7K/R6300v2/R6900，我们未来以 GPL 开放这些代码。

3. 合适的时期，开放 现在手里的 hack for R7K/R6300v2/R6900 的版本。

你可以看我们的插件代码，对固件的依赖已经很小很小了。相信不久就完全没有固件依赖了。

**Comment by goodbest** [comment]
Sounds to be a reasonable explanation.

Hope to see the independent Plugin Center soon.
