### ISSUE TITLE
关于1.5.1GFWlist模式下域名白名单未正确处理的问题反馈

### ISSUE THREAD

**Issue by FlyingGitHub** [koolshare/firmware#5]
由于2016-05-10版本的GFWlist误将v2ex.com放入，我在界面上的白名单中人工添加了v2ex.com，重启生效后，使用ipset  查询，发现该域名对应的ip地址还在gfwlist中，疑似Bug。

**Comment by houzi-** [comment]
请复现该问题:

具体做法：
```
ipset test {写入你的gfwlist的ipset集合名称} 120.52.13.12
EX: ipset test ss_spec_wan_ac 120.52.13.12
```
我输入以上命令，会有如下显示:(表明这个IP已经被导入到**ss_spec_wan_ac**这个集合里了)
```
120.52.13.12 is in set ss_spec_wan_ac
```
再者我输入一个不在该集合里面的情况是如下显示:
```
root@DD-WRT:~#ipset test ss_spec_wan_ac 103.245.222.133
103.245.222.133 is NOT in set ss_spec_wan_ac.
```

**Comment by FlyingGitHub** [comment]
ASUSWRT-Merlin RT-AC56U 380.59-X6.6.1 Fri Apr 29 08:31:23 UTC 2016
admin@RT-AC56R:/tmp/home/root# ipset --l
Name: router
Type: iphash
References: 1
Header: hashsize: 1024 probes: 8 resize: 50
Members:
151.101.100.133
172.217.25.227
216.58.220.227

Name: gfwlist
Type: iphash
References: 1
Header: hashsize: 1024 probes: 8 resize: 50
Members:
52.11.169.107
104.244.43.172
104.244.42.69
23.251.126.133（www.v2ex.com的ip地址）
以下略


Name: white_domain
Type: iphash
References: 0
Header: hashsize: 1024 probes: 8 resize: 50
Members:

**Comment by houzi-** [comment]
去**gfwlist.conf**把
···
server=/.dns.v2ex.com/127.0.0.1#7913
ipset=/.dns.v2ex.com/gfwlist
···
去掉看看

**Comment by FlyingGitHub** [comment]
去掉貌似解决了

**Comment by FlyingGitHub** [comment]
更新到2.0后，拿v2ex.com测试，还是不行。
首先在电脑上：

**Comment by FlyingGitHub** [comment]
恩，看错。相关ip已经放到white_domain中去了。抱歉。另提一个建议，白名单中的域名不要用国外dns进行解析，cdn判断会有问题。

**Comment by sadoneli** [comment]
如果不用国外DNS解析，那么翻墙会失效的，dns污染严重，你可以使用chinadns
