### ISSUE TITLE
6300v2 更改无线功率bug

### ISSUE THREAD

**Issue by gonejack** [koolshare/firmware#6]
开机设置好密码，无线密码后，修改功率。

X6.6.1版本更改无线功率后会反复重启开不了机，必须按Reset擦除配置后才能开机。

不知道是不是机器原因，上一个机子换更改无线功率后，2.4g信号弱到没有，刷回原厂也一样，跟商家换了机器。

现在这台机器改小无线功率就无法开机。

**Comment by sadoneli** [comment]
信号的强渡和质量并不完全取决于无线功率，追大功率可能带来高噪音等

**Comment by gonejack** [comment]
我不是追大功率，我是房间小想调低功率。

一调低就出问题。
