### ISSUE TITLE
建议固件加上摘要

### ISSUE THREAD

**Issue by fo2w** [koolshare/firmware#9]
首先十分感谢大家的辛勤付出

最近在下载固件的时候, 因为家里网络不稳定, 所以对下载的固件完整性不太放心
但是在网站上并没有看到md5或sha1等摘要文件, 对下载的文件没有办法验证

**Comment by sadoneli** [comment]
你好，我们的固件下载地址http://koolshare.io/ 每个固件都是有校验值的
